# Input configuration
input:
  type: "csv" # Options: "csv", "bigquery", "google_sheet", "text"
  source: "path/to/your/input.csv" # Path to file, BQ table, or Google Sheet
  url_column: "url" # Required for "csv", "bigquery", and "google_sheet"

# GCS Uploader configuration (optional)
# If project_id and bucket_name are not provided, upload is disabled.
gcs:
  project_id: "your-gcp-project-id"
  bucket_name: "your-gcs-bucket-name"
  destination_path: "downloads/"

# Downloader configuration
downloader:
  max_threads: 8
  max_retries: 3
  retry_wait_time: 5 # in seconds
  download_dir: "/tmp/cdown_downloads"

# Uploader configuration
uploader:
  max_threads: 8

# Resume functionality
resume:
  enabled: true